name: Release on Commit

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o AutoMap-linux main.go
      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o AutoMap-mac main.go
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o AutoMap-windows.exe main.go
      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Auto release v${{ github.run_number }}
          files: |
            AutoMap-linux
            AutoMap-mac
            AutoMap-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_TOKEN }}