name: Release on Commit

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o AutoMap-linux main.go
      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o AutoMap-mac main.go
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o AutoMap-windows.exe main.go
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Auto release ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        files: |
          AutoMap-linux
          AutoMap-mac
          AutoMap-windows.exe

